language: ruby
cache: bundler
bundler_args: --without benchmarks tools
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
script:
  - bundle exec rake
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.9.0
env:
  global:
    - COVERAGE=true
matrix:
  allow_failures:
    - rvm: rbx-3
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
