language: ruby
cache: bundler
bundler_args: --without benchmarks tools
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - jruby-9.2.7.0
env:
  global:
    - COVERAGE=true
  matrix:
    - DRY_LOGIC_FROM_MASTER=false
    - DRY_LOGIC_FROM_MASTER=true
    - DRY_TYPES_FROM_MASTER=false
    - DRY_TYPES_FROM_MASTER=true
matrix:
  allow_failures:
    - rvm: jruby-9.2.7.0
notifications:
  email: false
