name: ci

on:
  push:
    paths:
      - .github/workflows/custom_ci.yml
      - lib/**
      - spec/**
      - Gemfile
      - "*.gemspec"
    pull_requests:

jobs:
  tests-mri:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6.x", "2.5.x", "2.4.x"]
        dry_logic_from_master: ["false", "true"]
        dry_types_from_master: ["false", "true"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Run all tests
        env:
          DRY_LOGIC_FROM_MASTER: ${{matrix.dry_logic_from_master}}
          DRY_TYPES_FROM_MASTER: ${{matrix.dry_types_from_master}}
        run: |
          gem install bundler
          bundle config set without 'tools docs benchmarks'
          bundle install --jobs 4 --retry 3
          bundle exec rake
  tests-jruby:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dry_logic_from_master: ["false", "true"]
        dry_types_from_master: ["false", "true"]
    container:
      image: jruby:9.2.8
    steps:
      - uses: actions/checkout@v1
      - name: Install git
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git
      - name: Run all tests
        env:
          DRY_LOGIC_FROM_MASTER: ${{matrix.dry_logic_from_master}}
          DRY_TYPES_FROM_MASTER: ${{matrix.dry_types_from_master}}
        run: |
          bundle config set without 'tools docs benchmarks'
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
