name: Ruby

on: [push]

jobs:
  tests-mri:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.6.x", "2.5.x", "2.4.x"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Run all tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
  tests-jruby:
    runs-on: ubuntu-latest
    container:
      image: jruby:9.2.8
    steps:
      - uses: actions/checkout@v1
      - name: Run all tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
